services:
  traefik_reverse_proxy:
    container_name: traefik_reverse_proxy
    image: traefik:v2.9.6
    restart: always
    ports:
      # HTTP port
      - "80:80"
      # HTTPS port
      - "443:443"
      # traefik Web UI port
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/traefik/
      - ./letsencrypt/:/letsencrypt/
    networks:
      - traefik_reverse_proxy_network
networks:
  traefik_reverse_proxy_network:
    external: true
