services:
  traefik_reverse_proxy:
    container_name: traefik_reverse_proxy
    image: traefik:v2.9.6
    restart: always
    ports:
      # HTTP port
      # - "80:80"
      # HTTPS port
      - "443:443"
      # traefik Web UI port
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/traefik/
      - ./letsencrypt/:/letsencrypt/
    networks:
      - traefik_reverse_proxy_network
    environment:
      - TZ=Asia/Tokyo
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`${HOSTNAME}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certResolver=myresolver
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=auth
      - traefik.http.middlewares.auth.basicAuth.usersFile=/etc/traefik/.htpasswd
networks:
  traefik_reverse_proxy_network:
    external: true
