# Dynamic Configuration
http:
  routers:
    dashboard:
      rule: Host(`fmitty.net`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      tls:
        certResolver: myresolver
      service: api@internal
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        usersFile: /etc/traefik/.htpasswd